# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'game_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class GameForm(object):
    def setupUi(self, GameForm):
        if not GameForm.objectName():
            GameForm.setObjectName(u"GameForm")
        GameForm.resize(1010, 665)
        self.frame_jugador = QFrame(GameForm)
        self.frame_jugador.setObjectName(u"frame_jugador")
        self.frame_jugador.setGeometry(QRect(-150, -60, 1161, 771))
        self.frame_jugador.setStyleSheet(u"image: url(./assets/img/fondo_tablero_inicio.png);")
        self.frame_jugador.setFrameShape(QFrame.StyledPanel)
        self.frame_jugador.setFrameShadow(QFrame.Raised)
        self.lbl_titulo = QLabel(GameForm)
        self.lbl_titulo.setObjectName(u"lbl_titulo")
        self.lbl_titulo.setGeometry(QRect(60, 30, 191, 31))
        self.lbl_jugador = QLabel(GameForm)
        self.lbl_jugador.setObjectName(u"lbl_jugador")
        self.lbl_jugador.setGeometry(QRect(10, 190, 231, 31))
        self.lbl_edad = QLabel(GameForm)
        self.lbl_edad.setObjectName(u"lbl_edad")
        self.lbl_edad.setGeometry(QRect(10, 220, 231, 31))
        self.lbl_categoria = QLabel(GameForm)
        self.lbl_categoria.setObjectName(u"lbl_categoria")
        self.lbl_categoria.setGeometry(QRect(270, 40, 721, 71))
        self.btn_cat_historia = QPushButton(GameForm)
        self.btn_cat_historia.setObjectName(u"btn_cat_historia")
        self.btn_cat_historia.setGeometry(QRect(10, 280, 241, 51))
        font = QFont()
        font.setPointSize(14)
        self.btn_cat_historia.setFont(font)
        self.btn_cat_historia.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_cat_historia.setMouseTracking(False)
        self.btn_cat_historia.setFocusPolicy(Qt.WheelFocus)
        self.btn_cat_historia.setLayoutDirection(Qt.LeftToRight)
        self.btn_cat_historia.setAutoFillBackground(False)
        self.btn_cat_historia.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u"./assets/icon/icon_historia.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cat_historia.setIcon(icon)
        self.btn_cat_historia.setIconSize(QSize(30, 30))
        self.btn_cat_historia.setCheckable(False)
        self.btn_cat_historia.setAutoExclusive(False)
        self.btn_cat_historia.setAutoDefault(False)
        self.btn_cat_historia.setFlat(False)
        self.btn_cat_geografia = QPushButton(GameForm)
        self.btn_cat_geografia.setObjectName(u"btn_cat_geografia")
        self.btn_cat_geografia.setGeometry(QRect(10, 330, 241, 51))
        self.btn_cat_geografia.setFont(font)
        self.btn_cat_geografia.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_cat_geografia.setMouseTracking(False)
        self.btn_cat_geografia.setFocusPolicy(Qt.WheelFocus)
        self.btn_cat_geografia.setLayoutDirection(Qt.LeftToRight)
        self.btn_cat_geografia.setAutoFillBackground(False)
        self.btn_cat_geografia.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u"./assets/icon/icon_geografia.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cat_geografia.setIcon(icon1)
        self.btn_cat_geografia.setIconSize(QSize(30, 30))
        self.btn_cat_geografia.setCheckable(False)
        self.btn_cat_geografia.setAutoExclusive(False)
        self.btn_cat_geografia.setAutoDefault(False)
        self.btn_cat_geografia.setFlat(False)
        self.btn_cat_matematicas = QPushButton(GameForm)
        self.btn_cat_matematicas.setObjectName(u"btn_cat_matematicas")
        self.btn_cat_matematicas.setGeometry(QRect(10, 380, 241, 51))
        self.btn_cat_matematicas.setFont(font)
        self.btn_cat_matematicas.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_cat_matematicas.setMouseTracking(False)
        self.btn_cat_matematicas.setFocusPolicy(Qt.WheelFocus)
        self.btn_cat_matematicas.setLayoutDirection(Qt.LeftToRight)
        self.btn_cat_matematicas.setAutoFillBackground(False)
        self.btn_cat_matematicas.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u"./assets/icon/icon-matematicas.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cat_matematicas.setIcon(icon2)
        self.btn_cat_matematicas.setIconSize(QSize(30, 30))
        self.btn_cat_matematicas.setCheckable(False)
        self.btn_cat_matematicas.setAutoExclusive(False)
        self.btn_cat_matematicas.setAutoDefault(False)
        self.btn_cat_matematicas.setFlat(False)
        self.btn_cat_cultura = QPushButton(GameForm)
        self.btn_cat_cultura.setObjectName(u"btn_cat_cultura")
        self.btn_cat_cultura.setGeometry(QRect(10, 430, 241, 51))
        self.btn_cat_cultura.setFont(font)
        self.btn_cat_cultura.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_cat_cultura.setMouseTracking(False)
        self.btn_cat_cultura.setFocusPolicy(Qt.WheelFocus)
        self.btn_cat_cultura.setLayoutDirection(Qt.LeftToRight)
        self.btn_cat_cultura.setAutoFillBackground(False)
        self.btn_cat_cultura.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u"./assets/icon/icon_cultura.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cat_cultura.setIcon(icon3)
        self.btn_cat_cultura.setIconSize(QSize(30, 30))
        self.btn_cat_cultura.setCheckable(False)
        self.btn_cat_cultura.setAutoExclusive(False)
        self.btn_cat_cultura.setAutoDefault(False)
        self.btn_cat_cultura.setFlat(False)
        self.btn_cat_ingles = QPushButton(GameForm)
        self.btn_cat_ingles.setObjectName(u"btn_cat_ingles")
        self.btn_cat_ingles.setGeometry(QRect(10, 480, 241, 51))
        self.btn_cat_ingles.setFont(font)
        self.btn_cat_ingles.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_cat_ingles.setMouseTracking(False)
        self.btn_cat_ingles.setFocusPolicy(Qt.WheelFocus)
        self.btn_cat_ingles.setLayoutDirection(Qt.LeftToRight)
        self.btn_cat_ingles.setAutoFillBackground(False)
        self.btn_cat_ingles.setStyleSheet(u"")
        icon4 = QIcon()
        icon4.addFile(u"./assets/icon/icon_ingles.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_cat_ingles.setIcon(icon4)
        self.btn_cat_ingles.setIconSize(QSize(30, 30))
        self.btn_cat_ingles.setCheckable(False)
        self.btn_cat_ingles.setAutoExclusive(False)
        self.btn_cat_ingles.setAutoDefault(False)
        self.btn_cat_ingles.setFlat(False)
        self.btn_about = QPushButton(GameForm)
        self.btn_about.setObjectName(u"btn_about")
        self.btn_about.setGeometry(QRect(10, 590, 55, 55))
        self.btn_about.setFont(font)
        self.btn_about.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_about.setMouseTracking(False)
        self.btn_about.setFocusPolicy(Qt.WheelFocus)
        self.btn_about.setLayoutDirection(Qt.LeftToRight)
        self.btn_about.setAutoFillBackground(False)
        self.btn_about.setStyleSheet(u"")
        icon5 = QIcon()
        icon5.addFile(u"./assets/icon/icon_about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_about.setIcon(icon5)
        self.btn_about.setIconSize(QSize(50, 50))
        self.btn_about.setCheckable(False)
        self.btn_about.setAutoExclusive(False)
        self.btn_about.setAutoDefault(False)
        self.btn_about.setFlat(False)
        self.lbl_pregunta = QLabel(GameForm)
        self.lbl_pregunta.setObjectName(u"lbl_pregunta")
        self.lbl_pregunta.setGeometry(QRect(290, 100, 701, 121))
        self.lbl_pregunta.setTextFormat(Qt.RichText)
        self.lbl_pregunta.setWordWrap(True)
        self.opt_respuesta_1 = QRadioButton(GameForm)
        self.opt_respuesta_1.setObjectName(u"opt_respuesta_a")
        self.opt_respuesta_1.setGeometry(QRect(290, 230, 531, 41))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(False)
        font1.setWeight(50)
        self.opt_respuesta_1.setFont(font1)
        self.opt_respuesta_4 = QRadioButton(GameForm)
        self.opt_respuesta_4.setObjectName(u"opt_respuesta_d")
        self.opt_respuesta_4.setGeometry(QRect(290, 440, 531, 41))
        self.opt_respuesta_4.setFont(font1)
        self.opt_respuesta_2 = QRadioButton(GameForm)
        self.opt_respuesta_2.setObjectName(u"opt_respuesta_b")
        self.opt_respuesta_2.setGeometry(QRect(290, 300, 531, 41))
        self.opt_respuesta_2.setFont(font1)
        self.opt_respuesta_3 = QRadioButton(GameForm)
        self.opt_respuesta_3.setObjectName(u"opt_respuesta_c")
        self.opt_respuesta_3.setGeometry(QRect(290, 370, 531, 41))
        self.opt_respuesta_3.setFont(font1)
        self.opt_respuesta_0 = QRadioButton(GameForm)
        self.opt_respuesta_0.setObjectName(u"opt_respuesta_0")
        self.opt_respuesta_0.setGeometry(QRect(290, 500, 531, 41))
        self.opt_respuesta_0.setFont(font1)
        self.btn_next = QPushButton(GameForm)
        self.btn_next.setObjectName(u"btn_next")
        self.btn_next.setGeometry(QRect(874, 510, 101, 55))
        self.btn_next.setFont(font)
        self.btn_next.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_next.setMouseTracking(False)
        self.btn_next.setFocusPolicy(Qt.WheelFocus)
        self.btn_next.setLayoutDirection(Qt.LeftToRight)
        self.btn_next.setAutoFillBackground(False)
        self.btn_next.setStyleSheet(u"")
        icon6 = QIcon()
        icon6.addFile(u"./assets/icon/icon_next.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_next.setIcon(icon6)
        self.btn_next.setIconSize(QSize(50, 50))
        self.btn_next.setCheckable(False)
        self.btn_next.setAutoExclusive(False)
        self.btn_next.setAutoDefault(False)
        self.btn_next.setFlat(False)

        self.retranslateUi(GameForm)

        QMetaObject.connectSlotsByName(GameForm)
    # setupUi

    def retranslateUi(self, GameForm):
        GameForm.setWindowTitle(QCoreApplication.translate("GameForm", u"Poli-Preguntas Game", None))
        self.lbl_titulo.setText(QCoreApplication.translate("GameForm", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Poli Preguntas</span></p></body></html>", None))
        self.lbl_jugador.setText(QCoreApplication.translate("GameForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Miguelito</span></p></body></html>", None))
        self.lbl_edad.setText(QCoreApplication.translate("GameForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">32 a\u00f1os / Dif\u00edcil</span></p></body></html>", None))
        self.lbl_categoria.setText(QCoreApplication.translate("GameForm", u"<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\"></span></p></body></html>", None))
#if QT_CONFIG(accessibility)
        self.btn_cat_historia.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_cat_historia.setText(QCoreApplication.translate("GameForm", u"                     Historia", None))
#if QT_CONFIG(accessibility)
        self.btn_cat_geografia.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_cat_geografia.setText(QCoreApplication.translate("GameForm", u"                  Geograf\u00eda", None))
#if QT_CONFIG(accessibility)
        self.btn_cat_matematicas.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_cat_matematicas.setText(QCoreApplication.translate("GameForm", u"              Matem\u00e1ticas", None))
#if QT_CONFIG(accessibility)
        self.btn_cat_cultura.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_cat_cultura.setText(QCoreApplication.translate("GameForm", u"         Cultura General", None))
#if QT_CONFIG(accessibility)
        self.btn_cat_ingles.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_cat_ingles.setText(QCoreApplication.translate("GameForm", u"                       Ingl\u00e9s", None))
#if QT_CONFIG(accessibility)
        self.btn_about.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_about.setText("")
        self.lbl_pregunta.setText(QCoreApplication.translate("GameForm", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt;\"></span></p></body></html>", None))
        self.opt_respuesta_1.setText(QCoreApplication.translate("GameForm", u"Respuesta A", None))
        self.opt_respuesta_4.setText(QCoreApplication.translate("GameForm", u"Respuesta D", None))
        self.opt_respuesta_2.setText(QCoreApplication.translate("GameForm", u"Respuesta B", None))
        self.opt_respuesta_3.setText(QCoreApplication.translate("GameForm", u"Respuesta C", None))
        self.opt_respuesta_0.setText(QCoreApplication.translate("GameForm", u"Respuesta Nula", None))
# Edisión Especial: Componentes Enable
        self.btn_next.setVisible(False)
        self.opt_respuesta_1.setVisible(False)
        self.opt_respuesta_2.setVisible(False)
        self.opt_respuesta_3.setVisible(False)
        self.opt_respuesta_4.setVisible(False)
        self.opt_respuesta_0.setVisible(False)
        self.opt_respuesta_0.setChecked(True)
#if QT_CONFIG(accessibility)
        self.btn_next.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.btn_next.setText("")
    # retranslateUi

